/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\car.gltf 
Author: aron.jaeger (https://sketchfab.com/aron.jaeger)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-honda-nsx-6942000481834bad8f5c3c27bff95bc2
Title: Low Poly Honda NSX
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.33}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.004, 0]} scale={[3.326, 1.6, 7.099]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.011']} />
          </group>
          <group position={[2.776, -0.848, 4.694]} rotation={[0, 0, -1.518]} scale={[1, 0.581, 1]}>
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.008']} />
          </group>
          <group position={[-3, -0.848, -4.267]} rotation={[Math.PI, 0, 1.623]} scale={[1, 0.607, 1]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_18.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_19.geometry} material={materials['Material.008']} />
          </group>
          <group position={[-2.776, -0.848, 4.694]} rotation={[Math.PI, 0, 1.623]} scale={[1, 0.581, 1]}>
            <mesh geometry={nodes.Object_21.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_22.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_23.geometry} material={materials['Material.008']} />
          </group>
          <group position={[3, -0.848, -4.267]} rotation={[0, 0, -1.518]} scale={[1, 0.607, 1]}>
            <mesh geometry={nodes.Object_25.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_26.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_27.geometry} material={materials['Material.008']} />
          </group>
          <group position={[1.627, -1.284, -5.932]} rotation={[1.743, 0.017, 0.097]} scale={[0.3, 0.686, 0.3]}>
            <mesh geometry={nodes.Object_29.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.Object_30.geometry} material={materials['Material.014']} />
          </group>
          <mesh geometry={nodes.Object_32.geometry} material={materials.material_0} position={[0, -1.221, 7.167]} rotation={[2.917, 0, -Math.PI]} scale={[-1.091, 0.292, 0.039]} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} position={[0, -0.465, -7.123]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.091, 0.292, 0.039]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car.gltf')
