/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\road.gltf 
Author: Omer Bhatti (https://sketchfab.com/OmerBhatti)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/synthwave-80s-retro-style-foreground-5184125634af45a4b1a657b7d51c3d6e
Title: Synthwave | 80s retro style foreground
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/road.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Wireframe_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/road.gltf')
