/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\home.gltf 
Author: snovak (https://sketchfab.com/snovak)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neon-lobby-2-d3a7b0dfaae9479b83f7d28a9e080ad2
Title: Neon Lobby 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/home.gltf')
  return (
    <group {...props} dispose={null} scale={0.20}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.walls} position={[0.827, -0.476, 0.105]} scale={6.061} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} position={[16.884, 21.817, 0.006]} rotation={[-Math.PI, 0, 0]} scale={6.061} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material} position={[-14.519, 18.493, -4.231]} rotation={[2.756, 0, 0]} scale={6.359} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Material} position={[-51.018, 19.333, 4.259]} rotation={[-2.749, 0, 0]} scale={6.313} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Material} position={[-80.791, 21.817, 0.006]} rotation={[-Math.PI, 0, 0]} scale={6.061} />
    </group>
  )
}

useGLTF.preload('/home.gltf')
